services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: teambalancer
    ports:
      - "5432:5432"
    volumes:
      - teambalancer_pg:/var/lib/postgresql/data

volumes:
  teambalancer_pg:
